name: Deploy

on:
  - push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get release version
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV
      - uses: danielr1996/kubectl-action@1.0.0
        name: Deploy to Kubernetes
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: apply -f deploy.yaml
